name = "fra-collection-league"
compatibility_date = "2026-09-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fra-db-prod-20260930"
database_id = "4c090a01-d384-429c-a572-ab3d887caea5"
migrations_dir = "drizzle"
