name = "fra-collection-league"
compatibility_date = "2026-09-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fra-db-staging"
# staging — swap to prod UUID at cutover
database_id = "1e0f90ff-b12e-4368-bd07-fdb4b4160984"
migrations_dir = "drizzle"
