"use client";

import Link from "next/link";
import { FormEvent, KeyboardEvent, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { CardImage } from "./CardImage";
import { ManaCost } from "./ManaCost";
import { DeckAnalysis } from "./DeckAnalysis";
import { AltShell, type AltPlayer } from "./AltShell";
import type { CatalogCard, CollectionCard, DeckCard } from "@/lib/client";
import { BASIC_LANDS_GROUP, type PoolGroup } from "@/lib/deck-pool";

export type AltDeckViewMode = "images" | "list";
type Props = { initialCollapsedGroups?: string[]; profileId: string; profileName: string; players: AltPlayer[]; deckName: string; cards: DeckCard[]; catalog: CatalogCard[]; collection: CollectionCard[]; poolGroups: PoolGroup<CollectionCard>[]; basics: string[]; hiddenPoolCount: number; search: string; showOffColor: boolean; viewMode: AltDeckViewMode; status?: string; error?: string; commanderNames: string[]; eligibleCommanderNames: string[]; hasCommanderIdentity: boolean; onSearch: (value: string) => void; onShowOffColor: (value: boolean) => void; onViewMode: (mode: AltDeckViewMode) => void; onQty: (name: string, qty: number) => void; onCommander: (name: string) => void; onRename: (name: string) => void; onToggleStyle: () => void; isOffColor: (name: string, isBasic: boolean) => boolean };
const COLOR_CLASS: Record<string, string> = { White: "white", Blue: "blue", Black: "black", Red: "red", Green: "green", Colorless: "colorless", Multicolor: "multicolor" };
/** Shared with the Classic editor so collapsed pool groups survive a style switch. */
export const ALT_COLLAPSED_STORAGE_KEY = "fra-deck-collapsed";
type GroupStorage = Pick<Storage, "getItem" | "setItem">;

/** Reads persisted collapsed pool groups; bad JSON or unavailable storage yields none. */
export function readCollapsedGroups(storage: GroupStorage | undefined): Set<string> {
  try { const groups = JSON.parse(storage?.getItem(ALT_COLLAPSED_STORAGE_KEY) || "[]"); return new Set(Array.isArray(groups) ? groups.filter((group): group is string => typeof group === "string") : []); } catch { return new Set(); }
}
export function writeCollapsedGroups(storage: GroupStorage | undefined, groups: Set<string>) {
  try { storage?.setItem(ALT_COLLAPSED_STORAGE_KEY, JSON.stringify([...groups])); } catch { /* Keep the in-memory state. */ }
}
const browserStorage = () => { try { return window.localStorage; } catch { return undefined; } };

/** A collapsible pool group; the whole header is a button exposing aria-expanded. */
function AltPoolGroup({ title, dot, count, collapsed, onToggle, children }: { title: string; dot: string; count: string; collapsed: boolean; onToggle: () => void; children: ReactNode }) {
  const bodyId = `alt-pool-group-${title.toLowerCase().replace(/\s+/g, "-")}`;
  return <section className={`alt-section alt-deck-pool-group ${collapsed ? "collapsed" : ""}`}><h3><button type="button" className="alt-deck-group-toggle" aria-expanded={!collapsed} aria-controls={bodyId} onClick={onToggle}><span className="alt-deck-chevron" aria-hidden="true">{collapsed ? "▸" : "▾"}</span><i className={`alt-color-dot ${dot}`} /><span className="alt-deck-group-name">{title}</span><small>{count}</small></button></h3><div id={bodyId} hidden={collapsed}>{children}</div></section>;
}

export function AltDeckEditor(props: Props) {
  const { profileId, profileName, players, deckName, cards, catalog, collection, poolGroups, basics, hiddenPoolCount, search, showOffColor, viewMode, status, error, commanderNames, eligibleCommanderNames, hasCommanderIdentity, onSearch, onShowOffColor, onViewMode, onQty, onCommander, onRename, onToggleStyle, isOffColor, initialCollapsedGroups } = props;
  const [collapsed, setCollapsed] = useState<Set<string>>(() => new Set(initialCollapsedGroups));
  const [commanderOpen, setCommanderOpen] = useState(false); const [commanderSearch, setCommanderSearch] = useState(""); const [renaming, setRenaming] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null); const dialogRef = useRef<HTMLDivElement>(null); const commanderButtonRef = useRef<HTMLButtonElement>(null);
  const catalogMap = useMemo(() => new Map(catalog.map((card) => [card.name.toLowerCase(), card])), [catalog]); const deckMap = new Map(cards.map((card) => [card.name.toLowerCase(), card])); const ownedMap = new Map(collection.filter((card) => card.owned).map((card) => [card.name.toLowerCase(), card]));
  const total = cards.reduce((sum, card) => sum + card.qty, 0); const offColorCards = cards.filter((card) => isOffColor(card.name, card.isBasic)); const matchingCount = poolGroups.reduce((sum, group) => sum + group.entries.length, 0) + basics.length;
  const groups: Record<string, DeckCard[]> = { Creatures: [], Other: [], Lands: [] };
  cards.forEach((card) => { const type = catalogMap.get(card.name.toLowerCase())?.type.toLowerCase() || ""; groups[type.includes("land") || card.isBasic ? "Lands" : type.includes("creature") ? "Creatures" : "Other"].push(card); });

  useEffect(() => {
    const root = rootRef.current; const topbar = root?.querySelector<HTMLElement>(".alt-topbar");
    if (!root || !topbar || typeof ResizeObserver === "undefined") return;
    const update = () => root.style.setProperty("--alt-deck-topbar-h", `${topbar.offsetHeight}px`); update();
    const observer = new ResizeObserver(update); observer.observe(topbar); return () => observer.disconnect();
  }, []);

  useEffect(() => { if (!initialCollapsedGroups) setCollapsed(readCollapsedGroups(browserStorage())); }, [initialCollapsedGroups]);

  useEffect(() => {
    if (!commanderOpen) return;
    const focusable = () => [...(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), [href]') || [])]; focusable()[0]?.focus();
    const keydown = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); setCommanderOpen(false); return; } if (event.key !== "Tab") return; const items = focusable(); const first = items[0]; const last = items.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } };
    document.addEventListener("keydown", keydown); return () => { document.removeEventListener("keydown", keydown); commanderButtonRef.current?.focus(); };
  }, [commanderOpen]);

  const capFor = (name: string, basic = false) => basic ? 99 : ownedMap.get(name.toLowerCase())?.qty || 0; const quantity = (name: string) => deckMap.get(name.toLowerCase())?.qty || 0;
  const submitRename = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const name = String(new FormData(event.currentTarget).get("name") || "").trim(); if (name) onRename(name); setRenaming(false); };
  const renameKeys = (event: KeyboardEvent<HTMLInputElement>) => { if (event.key === "Escape") { event.preventDefault(); setRenaming(false); } };
  const viewSwitch = <div className="alt-deck-view-switch" role="group" aria-label="Deck editor view mode"><button type="button" aria-pressed={viewMode === "images"} onClick={() => onViewMode("images")}>Images</button><button type="button" aria-pressed={viewMode === "list"} onClick={() => onViewMode("list")}>List</button></div>;
  const title = <div className="alt-deck-title-row"><h1>{deckName}</h1>{renaming ? <form className="alt-create-inline" onSubmit={submitRename}><input autoFocus name="name" aria-label="Deck name" defaultValue={deckName} onKeyDown={renameKeys} /><button className="alt-pill alt-primary">Save</button><button className="alt-pill alt-outline" type="button" onClick={() => setRenaming(false)}>Cancel</button></form> : <button className="alt-rename" type="button" onClick={() => setRenaming(true)}>Rename</button>}</div>;
  const topRight = <><Link className="alt-pill alt-outline alt-back" href={`/p/${profileId}/decks`}>Back to decks</Link>{viewSwitch}</>;
  const stepper = (name: string, qty: number, cap: number, offColor: boolean) => <div className="alt-stepper alt-deck-quantity"><button type="button" disabled={qty === 0} aria-label={`Decrease ${name}`} onClick={() => onQty(name, Math.max(0, qty - 1))}>−</button><b>{qty}</b><button type="button" disabled={qty >= cap || offColor} aria-label={`Increase ${name}`} onClick={() => onQty(name, qty + 1)}>+</button></div>;
  const badge = (name: string) => <span className="alt-deck-off-color" aria-label={`${name} is outside the commander color identity`}>Off-color</span>;
  const storeCollapsed = (next: Set<string>) => { setCollapsed(next); writeCollapsedGroups(browserStorage(), next); };
  const toggleGroup = (group: string) => { const next = new Set(collapsed); if (next.has(group)) next.delete(group); else next.add(group); storeCollapsed(next); };
  const groupNames = [...poolGroups.map(({ group }) => group), ...(basics.length ? [BASIC_LANDS_GROUP] : [])]; const allCollapsed = groupNames.length > 0 && groupNames.every((group) => collapsed.has(group));
  const qtyBadge = (qty: number) => qty > 0 && <span className="alt-deck-qty-badge" aria-label={`${qty} in deck`}>{qty}</span>;
  const rarityGem = (info?: CatalogCard) => { const rarity = info?.rarity?.toLowerCase(); return rarity ? <span className="alt-deck-rarity" title={rarity}><i className={`alt-gem alt-rarity-${rarity}`} />{rarity[0].toUpperCase()}</span> : null; };
  // Pool images add one copy (Classic parity) until the owned cap; off-color cards cannot be added.
  const imageCard = (name: string, qty: number, cap: number, owned: string, offColor: boolean, adds: boolean) => { const info = catalogMap.get(name.toLowerCase()); const canAdd = adds && qty < cap && !offColor; return <article className={`alt-card ${offColor ? "is-off-color" : ""} ${canAdd ? "can-add" : ""} ${adds && !canAdd ? "at-cap" : ""}`} key={name}><div className="alt-card-visual"><CardImage name={name} catalog={info} onClick={canAdd ? () => onQty(name, qty + 1) : undefined} ariaLabel={adds ? `Add ${name} to deck` : undefined} />{info && <span className={`alt-rarity alt-rarity-${info.rarity.toLowerCase()}`}><i />{info.rarity}</span>}{qtyBadge(qty)}</div><strong title={name}>{name}</strong><small><i className={`alt-gem alt-rarity-${info?.rarity.toLowerCase() || "common"}`} />{qty} in deck · {owned}</small>{offColor && badge(name)}{stepper(name, qty, cap, offColor)}</article>; };
  const listCard = (name: string, qty: number, cap: number, owned: string, offColor: boolean) => { const info = catalogMap.get(name.toLowerCase()); return <article className={`alt-deck-list-row ${offColor ? "is-off-color" : ""}`} key={name}><div><span className="alt-deck-list-name"><strong>{name}</strong><ManaCost cost={info?.manaCost || ""} />{rarityGem(info)}</span><small>{qty} in deck · {owned}</small>{offColor && badge(name)}</div>{stepper(name, qty, cap, offColor)}</article>; };
  const renderCard = (name: string, qty: number, cap: number, owned: string, offColor: boolean, adds = false) => viewMode === "images" ? imageCard(name, qty, cap, owned, offColor, adds) : listCard(name, qty, cap, owned, offColor);
  const cardsClass = viewMode === "images" ? "alt-deck-card-grid" : "alt-card-list";
  const eligible = eligibleCommanderNames.filter((name) => name.toLowerCase().includes(commanderSearch.trim().toLowerCase())); const commanderOptions = [...commanderNames, ...eligible.filter((name) => !commanderNames.some((selected) => selected.toLowerCase() === name.toLowerCase()))];
  const commanderSection = <section className="alt-deck-commander" aria-label="Commander and color identity"><div className="alt-deck-commanders">{commanderNames.length ? commanderNames.map((name) => <div className="alt-deck-commander-card" key={name}><div><CardImage name={name} catalog={catalogMap.get(name.toLowerCase())} /></div><span><strong>{name}</strong><small>{catalogMap.get(name.toLowerCase())?.colorIdentity || "Colorless"}</small></span></div>) : <div className="alt-deck-commander-empty"><strong>Choose commanders</strong><small>Select up to two owned legendary creatures.</small></div>}</div><div className={`alt-deck-legality ${!hasCommanderIdentity ? "unchecked" : offColorCards.length ? "warning" : "passed"}`}><span aria-hidden="true">●</span>{!hasCommanderIdentity ? "Choose a commander to check color identity" : offColorCards.length ? <button type="button" onClick={() => document.querySelector(".alt-deck-off-color")?.scrollIntoView({ behavior: "smooth", block: "center" })}>{offColorCards.length} {offColorCards.length === 1 ? "card" : "cards"} outside commander colors</button> : "Color identity: no conflicts"}</div><button ref={commanderButtonRef} className="alt-pill alt-outline" type="button" onClick={() => setCommanderOpen(true)}>{commanderNames.length ? "Change commanders" : "Choose commanders"}</button></section>;
  // Like Classic, image mode mounts the deck analysis beside the commanders.
  const showAnalysis = viewMode === "images" && (commanderNames.length > 0 || cards.length > 0);

  return <div className="alt-deck-editor" ref={rootRef}><AltShell title={title} subtitle={`${profileName} · ${total} cards · commander excluded`} activeNav="decks" playerId={profileId} players={players} onToggleStyle={onToggleStyle} topRight={topRight}>
    {showAnalysis ? <div className="alt-deck-overview">{commanderSection}<section className="alt-deck-analysis" aria-label="Deck analysis"><div className="alt-section-head"><h2>Deck analysis</h2><span>Mana · types · curve</span></div><DeckAnalysis cards={cards} commanderNames={commanderNames} catalogMap={catalogMap} /></section></div> : commanderSection}
    {status && <p className="alt-deck-save-state" role="status">{status}</p>}{error && <p className="alt-notice error" role="alert">{error}</p>}
    <nav className="alt-deck-jumps" aria-label="Deck editor sections"><a href="#deck-contents">Deck contents</a><a href="#your-collection">Your collection</a></nav>
    <div className="alt-deck-workspace"><section id="deck-contents" className="alt-deck-pane alt-deck-contents"><div className="alt-section-head alt-deck-pane-head"><h2>Deck contents</h2><span>{total} cards · commander excluded</span></div>{cards.length === 0 ? <div className="alt-deck-empty"><strong>Your deck is empty.</strong><span>Add cards from your collection.</span></div> : Object.entries(groups).map(([group, entries]) => entries.length ? <section className="alt-section" key={group}><div className="alt-section-head"><h3>{group}</h3><span>{entries.reduce((sum, card) => sum + card.qty, 0)}</span></div><div className={cardsClass}>{entries.sort((a, b) => a.name.localeCompare(b.name)).map((card) => renderCard(card.name, card.qty, capFor(card.name, card.isBasic), card.isBasic ? "unlimited owned" : `${capFor(card.name)} owned`, isOffColor(card.name, card.isBasic)))}</div></section> : null)}</section>
      <section id="your-collection" className="alt-deck-pane alt-deck-pool"><div className="alt-deck-pool-toolbar"><div className="alt-section-head alt-deck-pane-head"><h2>Your collection</h2><span>{matchingCount} matching cards</span></div><label className="alt-search"><span aria-hidden="true">⌕</span><input type="search" value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Search owned cards" aria-label="Search owned cards" /></label><div className="alt-deck-pool-controls">{viewSwitch}{hasCommanderIdentity && <button type="button" className="alt-pill alt-outline" aria-pressed={showOffColor} onClick={() => onShowOffColor(!showOffColor)}>{showOffColor ? "Hide off-color" : `Show off-color (${hiddenPoolCount})`}</button>}{groupNames.length > 0 && <button type="button" className="alt-pill alt-outline alt-deck-collapse-all" onClick={() => storeCollapsed(allCollapsed ? new Set() : new Set(groupNames))}>{allCollapsed ? "Expand all" : "Collapse all"}</button>}</div></div>
        {!search.trim() && !collection.some((card) => card.owned) ? <div className="alt-deck-empty"><strong>No owned cards yet.</strong><Link href={`/p/${profileId}`}>Go to your collection</Link><span>Basic lands remain available below.</span></div> : matchingCount === 0 && <div className="alt-deck-empty">{search.trim() ? <><strong>No search matches.</strong><button type="button" onClick={() => onSearch("")}>Clear search</button></> : hiddenPoolCount ? <><strong>All cards are filtered by color identity.</strong><button type="button" onClick={() => onShowOffColor(true)}>Show off-color cards</button></> : <><strong>No cards match the current filters.</strong><span>Adjust the collection filters.</span></>}</div>}
        {poolGroups.map(({ group, entries }) => <AltPoolGroup key={group} title={group} dot={COLOR_CLASS[group]} count={`${entries.length} owned`} collapsed={collapsed.has(group)} onToggle={() => toggleGroup(group)}><div className={cardsClass}>{entries.map(({ card, offColor }) => renderCard(card.name, quantity(card.name), card.qty, `${card.qty} owned`, offColor, true))}</div></AltPoolGroup>)}
        {basics.length > 0 && <AltPoolGroup title={BASIC_LANDS_GROUP} dot="lands" count="Unlimited · max 99" collapsed={collapsed.has(BASIC_LANDS_GROUP)} onToggle={() => toggleGroup(BASIC_LANDS_GROUP)}><div className={cardsClass}>{basics.map((name) => renderCard(name, quantity(name), 99, "unlimited owned", false, true))}</div></AltPoolGroup>}
      </section></div>
    {commanderOpen && <div className="alt-commander-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setCommanderOpen(false); }}><div ref={dialogRef} className="alt-commander-dialog" role="dialog" aria-modal="true" aria-labelledby="alt-commander-title"><header><div><h2 id="alt-commander-title">Choose commanders</h2><small>{commanderNames.length} of 2 selected</small></div><button className="alt-pill alt-outline" type="button" onClick={() => setCommanderOpen(false)}>Close</button></header><label className="alt-search"><span aria-hidden="true">⌕</span><input type="search" value={commanderSearch} onChange={(event) => setCommanderSearch(event.target.value)} placeholder="Search commanders" aria-label="Search commanders" /></label><div className="alt-commander-options">{commanderOptions.map((name) => { const selected = commanderNames.some((entry) => entry.toLowerCase() === name.toLowerCase()); return <article className={`alt-commander-option ${selected ? "selected" : ""}`} key={name}><div><CardImage name={name} catalog={catalogMap.get(name.toLowerCase())} /></div><span><strong>{name}</strong><small>{selected ? "Selected commander" : catalogMap.get(name.toLowerCase())?.colorIdentity || "Colorless"}</small></span><button className={`alt-pill ${selected ? "alt-danger alt-outline" : "alt-primary"}`} type="button" disabled={!selected && commanderNames.length >= 2} onClick={() => onCommander(name)}>{selected ? "Remove" : "Select"}</button></article>; })}{commanderOptions.length === 0 && <p className="alt-deck-empty">No eligible commanders match your search.</p>}</div><footer><button className="alt-pill alt-primary" type="button" onClick={() => setCommanderOpen(false)}>Done</button></footer></div></div>}
  </AltShell></div>;
}
