// Ambient declarations for Cloudflare Workers runtime modules and globals.
// Proper typed versions are generated by `cf workers types` into .cloudflare/types/.
// These stubs keep tsc happy until those generated types are available.

// D1Database global — normally provided by @cloudflare/workers-types
interface D1Database {
  prepare(query: string): D1PreparedStatement;
  dump(): Promise<ArrayBuffer>;
  batch<T = unknown>(statements: D1PreparedStatement[]): Promise<D1Result<T>[]>;
  exec(query: string): Promise<D1ExecResult>;
}
interface D1PreparedStatement {
  bind(...values: unknown[]): D1PreparedStatement;
  first<T = unknown>(colName?: string): Promise<T | null>;
  run<T = unknown>(): Promise<D1Result<T>>;
  all<T = unknown>(): Promise<D1Result<T>>;
  raw<T = unknown[]>(): Promise<T[]>;
}
interface D1Result<T = unknown> {
  results: T[];
  success: boolean;
  meta: Record<string, unknown>;
  error?: string;
}
interface D1ExecResult {
  count: number;
  duration: number;
}

declare module "cloudflare:workers" {
  /** Worker bindings injected by the Cloudflare runtime. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const env: Record<string, any>;
}
